"""Day 3: validation of the day-1 orbital model against real recorded passes.

The passes are not generated by this lab. They come from the SatNOGS volunteer
ground-station network, pinned by observation ID in ``manifest.json`` so the
download is reproducible, and each one carries the TLE that was current when the
station recorded it.
"""
